### ISSUE TITLE
how to visualize the result with "episode_reward"

### ISSUE THREAD

**Issue by 937552416** [stevenpjg/ddpg-aigym#10]
hi steven,my system do not have Mujoco,so I combine your code with nrod80's code(https://github.com/nrod80/ddpg-for-openai) to build a new code.But I could not visualize the result.Could you told where is the visualize API?

**Comment by stevenpjg** [comment]
The total rewards at each episode get stored in the  [episode_reward.txt](https://github.com/stevenpjg/ddpg-aigym/blob/master/episode_reward.txt) . Once the rewards are stored, you can use the  [result_plot.py](https://github.com/stevenpjg/ddpg-aigym/blob/master/result_plot.py) to visualize the learning curve
