### ISSUE TITLE
Error with GLEW initialization

### ISSUE THREAD

**Issue by williamissirius** [stevenpjg/ddpg-aigym#14]
This is the output that I got:
Creating window glfw
ERROR: GLEW initalization error: Missing GL version
My setup:
Python3.5, Ubuntu 16.04, gym from openai official github.

**Comment by ganyeshprasanna** [comment]
Hi,
Try running this : export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so:/usr/lib/nvidia-384/libGL.so 
in your terminal and then run the code.
-Ganesh

**Comment by stevenpjg** [comment]
Resolving. Please reopen if you still face issues.
