### ISSUE TITLE
Need help to understand a step

### ISSUE THREAD

**Issue by sarvghotra** [stevenpjg/ddpg-aigym#2]
Could you please explain this 3 in this line https://github.com/stevenpjg/ddpg-aigym/blob/master/actor_net.py#L62 ?

**Comment by stevenpjg** [comment]
tanh function at the output layer returns a value from -1 to +1 . The action_space of the specific environment used for testing (inverted pendulum) ranges from -3 to +3 . So, 3 was multiplied with the final tanh ouput layer. 

Now, I have generalized with a action_bound variable
