### ISSUE TITLE
Number of nodes in a hidden layer are different from the DDPG paper

### ISSUE THREAD

**Issue by sarvghotra** [stevenpjg/ddpg-aigym#3]
https://github.com/stevenpjg/ddpg-aigym/blob/master/critic_net.py#L58
According to the paper this should be 300.

**Comment by stevenpjg** [comment]
Fixed! 2nd layer has been changed to 300 as mentioned in the ddpg-paper. The output of the actor-net is always near the extreme i.e) either near -3 or +3. Still trying to figure out the error. Feel free to contribute to this code.
