### ISSUE TITLE
Error, when ran for other environments like reacher-v1.

### ISSUE THREAD

**Issue by sarvghotra** [stevenpjg/ddpg-aigym#5]
I tried to run this code for Reacher-v1 and Swimmer-v1 but it threw an error due to this [line](https://github.com/stevenpjg/ddpg-aigym/blob/master/main.py#L42). 
_ValueError: total size of new array must be unchanged_

Could you please also explain why do you even need this step for InvertedPendulum ?

**Comment by stevenpjg** [comment]
Fixed! I would recommend you to add one more wrapper to scale your reward, as reacher and swimmer takes so long to train.

This is the step where action is computed using actor network model.
