### ISSUE TITLE
It si very very slow for Pendulum-v0 of classic control environment

### ISSUE THREAD

**Issue by sarvghotra** [stevenpjg/ddpg-aigym#6]
I ran this code for Pendulum-v0 environment, its too too slow on this particular environment. But its considerably faster on InvertedPendulum-v1. Do you have any idea why is it so ?

**Comment by stevenpjg** [comment]
It should be fine now. You can accelerate it further using a small wrapper to use normalized environments and reward scaling([link](http://www0.cs.ucl.ac.uk/staff/d.silver/web/Publications_files/popart.pdf)), as you mentioned earlier in your discussion.
